export type Category = 'F2L' | 'OLL' | 'PLL' | 'Advanced';

export interface Algorithm {
  id: string;
  name: string;
  category: Category;
  subCategory?: string;
  alg: string;
  alts: string[];
  moves: number;
  recognition: string;
  fingertricks?: string;
  popularity: number;
  caseShape?: string;
  arrows?: string;
  /** Extra learning tips shown on the case detail page. */
  notes?: string;
}

// ───────────── F2L ─────────────
export const f2lAlgorithms: Algorithm[] = [
  {
    id: 'f2l-1',
    name: 'F2L Case 1 – Basic Insert',
    category: 'F2L',
    subCategory: 'Basic',
    alg: "U R U' R'",
    alts: ["y' U' L' U L"],
    moves: 4,
    recognition: 'White-on-top corner, edge in UFR',
    fingertricks: 'Push with index on R, pull back',
    popularity: 10,
    caseShape: 'basic',
  },
  {
    id: 'f2l-2',
    name: 'F2L Case 2 – Corner in Front',
    category: 'F2L',
    subCategory: 'Basic',
    alg: "F' U F",
    alts: ["y R U' R'"],
    moves: 3,
    recognition: 'Corner on front face, edge in UF slot',
    fingertricks: 'Flick F with ring finger',
    popularity: 9,
    caseShape: 'basic',
  },
  {
    id: 'f2l-3',
    name: 'F2L Case 3 – Corner Left',
    category: 'F2L',
    subCategory: 'Basic',
    alg: "U' L' U L",
    alts: ["y U R U' R'"],
    moves: 4,
    recognition: 'Corner at UFL, edge mismatch',
    fingertricks: "Left hand L' move",
    popularity: 8,
    caseShape: 'basic',
  },
  {
    id: 'f2l-4',
    name: 'F2L Case 4 – Paired Pieces',
    category: 'F2L',
    subCategory: 'Advanced',
    alg: "U2 R U2 R'",
    alts: ["y' U2 L' U2 L"],
    moves: 4,
    recognition: 'Corner and edge already paired in U layer',
    fingertricks: 'Double U flick',
    popularity: 7,
    caseShape: 'paired',
  },
  {
    id: 'f2l-5',
    name: 'F2L Case 5 – Corner Twisted',
    category: 'F2L',
    subCategory: 'Intermediate',
    alg: "R U R' U' R U R'",
    alts: ["F' U' F U F' U' F"],
    moves: 7,
    recognition: 'Corner in correct slot but twisted',
    fingertricks: 'Continuous RU rhythm',
    popularity: 8,
    caseShape: 'twisted',
  },
  {
    id: 'f2l-6',
    name: 'F2L Case 6 – Edge Flipped',
    category: 'F2L',
    subCategory: 'Intermediate',
    alg: "U R U' R' U' F' U F",
    alts: ["R U2 R' U' R U R'"],
    moves: 8,
    recognition: 'Edge flipped in slot, corner correct',
    fingertricks: 'RU then F trigger',
    popularity: 6,
    caseShape: 'flipped',
  },
  {
    id: 'f2l-7',
    name: 'F2L Case 7 – Slot Occupied',
    category: 'F2L',
    subCategory: 'Slot Occupied',
    alg: "R U' R' U R U' R'",
    alts: ["U' R U R' U R U' R'"],
    moves: 7,
    recognition: 'Another pair occupies the target slot',
    fingertricks: 'Standard RU rhythm',
    popularity: 5,
    caseShape: 'occupied',
  },
  {
    id: 'f2l-8',
    name: 'F2L Case 8 – Both in Slot',
    category: 'F2L',
    subCategory: 'Slot Occupied',
    alg: "R U2 R' U2 R U' R'",
    alts: ["y' L' U2 L U2 L' U L"],
    moves: 7,
    recognition: 'Corner and edge both in wrong slot',
    fingertricks: 'Wide double-U',
    popularity: 5,
    caseShape: 'occupied',
  },
  {
    id: 'f2l-9',
    name: 'F2L Case 9 – White Top, Edge Flipped',
    category: 'F2L',
    subCategory: 'White on Top',
    alg: "R U' R' U' R U R'",
    alts: [],
    moves: 7,
    recognition: 'White on top, edge at UR but flipped (wrong orientation)',
    popularity: 6,
    caseShape: 'basic',
  },
  {
    id: 'f2l-10',
    name: 'F2L Case 10 – White Top, AUF Needed',
    category: 'F2L',
    subCategory: 'White on Top',
    alg: "U2 R U' R' U R U' R'",
    alts: [],
    moves: 8,
    recognition: 'White on top, edge at UL — needs two U moves to align',
    popularity: 5,
    caseShape: 'basic',
  },
  {
    id: 'f2l-11',
    name: 'F2L Case 11 – White Top, Corner Back',
    category: 'F2L',
    subCategory: 'White on Top',
    alg: "U R U2 R' U R U' R'",
    alts: [],
    moves: 8,
    recognition: 'White on top, corner at UBR position',
    popularity: 5,
    caseShape: 'basic',
  },
  {
    id: 'f2l-12',
    name: 'F2L Case 12 – White Front, Edge Correct',
    category: 'F2L',
    subCategory: 'White on Front',
    alg: "R U R' U' F' U F",
    alts: [],
    moves: 7,
    recognition: 'White facing front, edge at UF and matching',
    popularity: 7,
    caseShape: 'basic',
  },
  {
    id: 'f2l-13',
    name: 'F2L Case 13 – White Front, Edge Flipped',
    category: 'F2L',
    subCategory: 'White on Front',
    alg: "F' U' F U F' U' F",
    alts: [],
    moves: 7,
    recognition: 'White facing front, edge at UF but flipped',
    popularity: 6,
    caseShape: 'basic',
  },
  {
    id: 'f2l-14',
    name: 'F2L Case 14 – White Front, AUF Right',
    category: 'F2L',
    subCategory: 'White on Front',
    alg: "U R U R' U' F' U F",
    alts: [],
    moves: 8,
    recognition: 'White facing front, edge at UR (needs AUF)',
    popularity: 5,
    caseShape: 'basic',
  },
  {
    id: 'f2l-15',
    name: 'F2L Case 15 – White Front, Edge Away',
    category: 'F2L',
    subCategory: 'White on Front',
    alg: "U' F' U' F U F' U' F",
    alts: [],
    moves: 8,
    recognition: 'White facing front, edge at UL or UB',
    popularity: 5,
    caseShape: 'basic',
  },
  {
    id: 'f2l-16',
    name: 'F2L Case 16 – White Front, Connected',
    category: 'F2L',
    subCategory: 'White on Front',
    alg: "U' R U' R' U2 R U' R'",
    alts: [],
    moves: 8,
    recognition: 'White facing front, pieces connected but AUF needed',
    popularity: 6,
    caseShape: 'basic',
  },
  {
    id: 'f2l-17',
    name: 'F2L Case 17 – White Right, Edge Matching',
    category: 'F2L',
    subCategory: 'White on Side',
    alg: "R U' R' U R U' R'",
    alts: [],
    moves: 7,
    recognition: 'White facing right, edge at UR and matching front color',
    popularity: 7,
    caseShape: 'basic',
  },
  {
    id: 'f2l-18',
    name: 'F2L Case 18 – White Right, Edge Flipped',
    category: 'F2L',
    subCategory: 'White on Side',
    alg: "R U R' U' R U R'",
    alts: [],
    moves: 7,
    recognition: 'White facing right, edge at UR but flipped',
    popularity: 6,
    caseShape: 'basic',
  },
  {
    id: 'f2l-19',
    name: 'F2L Case 19 – White Right, AUF Needed',
    category: 'F2L',
    subCategory: 'White on Side',
    alg: "U' R U' R' U R U' R'",
    alts: [],
    moves: 8,
    recognition: 'White facing right, edge not at UR position',
    popularity: 5,
    caseShape: 'basic',
  },
  {
    id: 'f2l-20',
    name: 'F2L Case 20 – White Right, Edge Far',
    category: 'F2L',
    subCategory: 'White on Side',
    alg: "U2 R U' R' U R U' R'",
    alts: [],
    moves: 8,
    recognition: 'White facing right, edge at UB (opposite side)',
    popularity: 5,
    caseShape: 'basic',
  },
  {
    id: 'f2l-21',
    name: 'F2L Case 21 – White Right, Edge Flipped Far',
    category: 'F2L',
    subCategory: 'White on Side',
    alg: "U R U R' U' R U R'",
    alts: [],
    moves: 8,
    recognition: 'White facing right, edge flipped at non-matching position',
    popularity: 5,
    caseShape: 'basic',
  },
  {
    id: 'f2l-22',
    name: 'F2L Case 22 – White Left Side',
    category: 'F2L',
    subCategory: 'White on Side',
    alg: "y' L' U' L U L' U' L",
    alts: ["U' F' U F U' F' U F"],
    moves: 7,
    recognition: 'White facing left, use mirror of right-side algorithms',
    popularity: 6,
    caseShape: 'basic',
  },
  {
    id: 'f2l-23',
    name: 'F2L Case 23 – White Left, AUF',
    category: 'F2L',
    subCategory: 'White on Side',
    alg: "y' L' U L U' L' U' L",
    alts: ["B' U B U' B' U' B"],
    moves: 7,
    recognition: 'White facing left, edge with AUF correction needed',
    popularity: 5,
    caseShape: 'basic',
  },
  {
    id: 'f2l-24',
    name: 'F2L Case 24 – White Back Corner',
    category: 'F2L',
    subCategory: 'White on Top',
    alg: "U' R U2 R' U' R U' R'",
    alts: [],
    moves: 8,
    recognition: 'White on top with corner pointing back, edge needs AUF',
    popularity: 5,
    caseShape: 'basic',
  },
  {
    id: 'f2l-25',
    name: 'F2L Case 25 – Corner & Edge in U Layer',
    category: 'F2L',
    subCategory: 'Edge in Slot',
    alg: "R U' R' U R U' R'",
    alts: [],
    moves: 7,
    recognition: 'Corner and edge both in the U layer, white on top — pair them up and insert into the front-right slot.',
    popularity: 7,
    caseShape: 'slot',
  },
  {
    id: 'f2l-26',
    name: 'F2L Case 26 – Edge in Slot, Corner White Front',
    category: 'F2L',
    subCategory: 'Edge in Slot',
    alg: "R U R'",
    alts: [],
    moves: 3,
    recognition: 'Edge in slot correct, corner in U white facing front-right',
    popularity: 8,
    caseShape: 'slot',
  },
  {
    id: 'f2l-27',
    name: 'F2L Case 27 – Corner & Edge in U, White Side',
    category: 'F2L',
    subCategory: 'Edge in Slot',
    alg: "R U2 R' U' R U R'",
    alts: [],
    moves: 7,
    recognition: 'Corner and edge in the U layer with white facing the side — pair and insert into the front-right slot.',
    popularity: 6,
    caseShape: 'slot',
  },
  {
    id: 'f2l-28',
    name: 'F2L Case 28 – Edge Flipped in Slot, Corner Up',
    category: 'F2L',
    subCategory: 'Edge in Slot',
    alg: "R U' R' U R U' R' U R U' R'",
    alts: [],
    moves: 11,
    recognition: 'Edge in FR slot but flipped; corner in U layer white up',
    popularity: 5,
    caseShape: 'slot',
  },
  {
    id: 'f2l-29',
    name: 'F2L Case 29 – Edge Flipped in Slot, Corner Front',
    category: 'F2L',
    subCategory: 'Edge in Slot',
    alg: "R U R' U' R U R' U' R U R'",
    alts: [],
    moves: 11,
    recognition: 'Edge in slot flipped, corner in U white facing front',
    popularity: 4,
    caseShape: 'slot',
  },
  {
    id: 'f2l-30',
    name: 'F2L Case 30 – Edge Flipped in Slot, Corner Side',
    category: 'F2L',
    subCategory: 'Edge in Slot',
    alg: "R U2 R' U' R U R' U' R U R'",
    alts: [],
    moves: 11,
    recognition: 'Edge in slot flipped, corner in U white facing side',
    popularity: 4,
    caseShape: 'slot',
  },
  {
    id: 'f2l-31',
    name: 'F2L Case 31 – Corner in Slot, Edge in U Matching',
    category: 'F2L',
    subCategory: 'Corner in Slot',
    alg: "U' R U R' U R U' R'",
    alts: [],
    moves: 8,
    recognition: 'Corner in FR slot correctly; edge in U layer matching front color',
    popularity: 6,
    caseShape: 'slot',
  },
  {
    id: 'f2l-32',
    name: 'F2L Case 32 – Corner in Slot, Edge in U Not Matching',
    category: 'F2L',
    subCategory: 'Corner in Slot',
    alg: "U R U' R' U' R U R'",
    alts: [],
    moves: 8,
    recognition: 'Corner in slot correctly; edge in U layer but color does not match',
    popularity: 6,
    caseShape: 'slot',
  },
  {
    id: 'f2l-33',
    name: 'F2L Case 33 – Corner in Slot Wrong Orientation',
    category: 'F2L',
    subCategory: 'Corner in Slot',
    alg: "R U' R' U R U R' U R U' R'",
    alts: [],
    moves: 11,
    recognition: 'Corner in FR slot but wrong orientation; edge in U layer',
    popularity: 5,
    caseShape: 'slot',
  },
  {
    id: 'f2l-34',
    name: 'F2L Case 34 – Corner in Slot Twisted, Edge Away',
    category: 'F2L',
    subCategory: 'Corner in Slot',
    alg: "R U2 R' U R U' R'",
    alts: [],
    moves: 7,
    recognition: 'Corner in wrong slot orientation, edge at UB needing realignment',
    popularity: 5,
    caseShape: 'slot',
  },
  {
    id: 'f2l-35',
    name: 'F2L Case 35 – Corner Twisted in Slot, Edge Front',
    category: 'F2L',
    subCategory: 'Corner in Slot',
    alg: "R' F R F' R U' R'",
    alts: [],
    moves: 7,
    recognition: 'Corner in slot twisted, edge in UF position',
    popularity: 5,
    caseShape: 'slot',
  },
  {
    id: 'f2l-36',
    name: 'F2L Case 36 – Both Misplaced, Standard',
    category: 'F2L',
    subCategory: 'Slot Occupied',
    alg: "R U' R' U2 R U R' U R U' R'",
    alts: [],
    moves: 11,
    recognition: 'Both corner and edge in wrong slots; standard misplace',
    popularity: 4,
    caseShape: 'occupied',
  },
  {
    id: 'f2l-37',
    name: 'F2L Case 37 – Both Misplaced, Flipped Edge',
    category: 'F2L',
    subCategory: 'Slot Occupied',
    alg: "R U R' U' R U2 R' U R U' R'",
    alts: [],
    moves: 11,
    recognition: 'Both misplaced; edge is also flipped requiring extra moves',
    popularity: 4,
    caseShape: 'occupied',
  },
  {
    id: 'f2l-38',
    name: 'F2L Case 38 – Both Wrong, With F Trigger',
    category: 'F2L',
    subCategory: 'Slot Occupied',
    alg: "R U' R' U R U' R' U' F' U F",
    alts: [],
    moves: 11,
    recognition: 'Both wrong in slot; solved with F-trigger ending',
    popularity: 4,
    caseShape: 'occupied',
  },
  {
    id: 'f2l-39',
    name: 'F2L Case 39 – Wide Move Pair',
    category: 'F2L',
    subCategory: 'Advanced',
    alg: "r U' r' U r U r'",
    alts: [],
    moves: 7,
    recognition: 'Use wide r move to insert pair efficiently',
    fingertricks: 'Pinky on r, continuous motion',
    popularity: 6,
    caseShape: 'wide',
  },
  {
    id: 'f2l-40',
    name: 'F2L Case 40 – Wide Move Mirror',
    category: 'F2L',
    subCategory: 'Advanced',
    alg: "l' U l U' l' U' l",
    alts: [],
    moves: 7,
    recognition: 'Mirror wide l move insert',
    popularity: 5,
    caseShape: 'wide',
  },
  {
    id: 'f2l-41',
    name: 'F2L Case 41 – Back Slot Insert',
    category: 'F2L',
    subCategory: 'Advanced',
    alg: "U' B' U B U' B' U B",
    alts: ["y2 U' R' U R U' R' U R"],
    moves: 8,
    recognition: 'Pair inserts into back slot; B-face version or rotate to use R',
    popularity: 4,
    caseShape: 'basic',
  },
];

// ───────────── OLL ─────────────
export const ollAlgorithms: Algorithm[] = [
  {
    id: 'oll-1',
    name: 'OLL 1 – Dot',
    category: 'OLL',
    subCategory: 'Dot',
    alg: "R U2 R2 F R F' U2 R' F R F'",
    alts: [],
    moves: 11,
    recognition: 'No edges oriented; full dot pattern on top',
    popularity: 4,
    caseShape: 'dot',
  },
  {
    id: 'oll-2',
    name: 'OLL 2 – Dot Diagonal',
    category: 'OLL',
    subCategory: 'Dot',
    alg: "F R U R' U' F' f R U R' U' f'",
    alts: [],
    moves: 12,
    recognition: 'Dot with two diagonal corners oriented',
    popularity: 3,
    caseShape: 'dot',
  },
  {
    id: 'oll-3',
    name: 'OLL 3 – Dot, Two Edges Back/Left',
    category: 'OLL',
    subCategory: 'Dot',
    alg: "f R U R' U' f' U' F R U R' U' F'",
    alts: [],
    moves: 13,
    recognition: 'Dot with two non-adjacent edges hinting at back/left',
    popularity: 3,
    caseShape: 'dot',
  },
  {
    id: 'oll-4',
    name: 'OLL 4 – Dot, Two Edges Adjacent',
    category: 'OLL',
    subCategory: 'Dot',
    alg: "f R U R' U' f' U F R U R' U' F'",
    alts: [],
    moves: 13,
    recognition: 'Dot with two adjacent edges pointing out',
    popularity: 3,
    caseShape: 'dot',
  },
  {
    id: 'oll-5',
    name: 'OLL 5 – Block Shape Right',
    category: 'OLL',
    subCategory: 'Block',
    alg: "r' U2 R U R' U r",
    alts: [],
    moves: 7,
    recognition: 'Two adjacent edges + one corner forming a square on right',
    fingertricks: 'Wide r pull, fast',
    popularity: 7,
    caseShape: 'Block',
  },
  {
    id: 'oll-6',
    name: 'OLL 6 – Block Shape Left',
    category: 'OLL',
    subCategory: 'Block',
    alg: "r U2 R' U' R U' r'",
    alts: [],
    moves: 7,
    recognition: 'Square pattern mirrored to the left',
    fingertricks: 'Wide r push, fast',
    popularity: 7,
    caseShape: 'Block',
  },
  {
    id: 'oll-7',
    name: 'OLL 7 – Small Lightning Right',
    category: 'OLL',
    subCategory: 'Lightning',
    alg: "r U R' U R U2 r'",
    alts: [],
    moves: 7,
    recognition: 'Lightning bolt shape pointing right on top face',
    fingertricks: 'r push → RU → r pull back',
    popularity: 8,
    caseShape: 'Lightning',
  },
  {
    id: 'oll-8',
    name: 'OLL 8 – Small Lightning Left',
    category: 'OLL',
    subCategory: 'Lightning',
    alg: "r' U' R U' R' U2 r",
    alts: [],
    moves: 7,
    recognition: 'Lightning bolt pointing left on top face',
    popularity: 8,
    caseShape: 'Lightning',
  },
  {
    id: 'oll-9',
    name: 'OLL 9 – Fish Right',
    category: 'OLL',
    subCategory: 'Fish',
    alg: "R U R' U' R' F R2 U R' U' F'",
    alts: [],
    moves: 11,
    recognition: 'Fish shape with head pointing toward front-right',
    popularity: 6,
    caseShape: 'Fish',
  },
  {
    id: 'oll-10',
    name: 'OLL 10 – Fish Left',
    category: 'OLL',
    subCategory: 'Fish',
    alg: "R U R' U R' F R F' R U2 R'",
    alts: [],
    moves: 11,
    recognition: 'Fish shape with tail toward back-right',
    popularity: 6,
    caseShape: 'Fish',
  },
  {
    id: 'oll-11',
    name: 'OLL 11 – Lightning Wide Right',
    category: 'OLL',
    subCategory: 'Lightning',
    alg: "r U R' U R' F R F' R U2 r'",
    alts: [],
    moves: 11,
    recognition: 'S-curve shape on top with wide move recognition',
    popularity: 5,
    caseShape: 'Lightning',
  },
  {
    id: 'oll-12',
    name: 'OLL 12 – Lightning Wide Left',
    category: 'OLL',
    subCategory: 'Lightning',
    alg: "M' R' U' R U' R' U2 R U' M",
    alts: [],
    moves: 9,
    recognition: 'S-curve mirrored; M-slice approach',
    popularity: 5,
    caseShape: 'Lightning',
  },
  {
    id: 'oll-13',
    name: 'OLL 13 – L Shape Right',
    category: 'OLL',
    subCategory: 'L',
    alg: "F U R U' R2 F' R U R U' R'",
    alts: [],
    moves: 11,
    recognition: 'Knight-move shape; two stickers on right front corner',
    popularity: 6,
    caseShape: 'L',
  },
  {
    id: 'oll-14',
    name: 'OLL 14 – L Shape Left',
    category: 'OLL',
    subCategory: 'L',
    alg: "R' F R U R' F' R F U' F'",
    alts: [],
    moves: 10,
    recognition: 'Knight-move shape mirrored to the left',
    popularity: 6,
    caseShape: 'L',
  },
  {
    id: 'oll-15',
    name: 'OLL 15 – P Right',
    category: 'OLL',
    subCategory: 'P',
    alg: "r' U' r R' U' R U r' U r",
    alts: [],
    moves: 9,
    recognition: 'P shape: bar on back, one sticker right front',
    fingertricks: 'Wide r move combo',
    popularity: 7,
    caseShape: 'P',
  },
  {
    id: 'oll-16',
    name: 'OLL 16 – P Left',
    category: 'OLL',
    subCategory: 'P',
    alg: "r U r' R U R' U' r U' r'",
    alts: [],
    moves: 9,
    recognition: 'P shape mirrored; bar on back, sticker left front',
    popularity: 7,
    caseShape: 'P',
  },
  {
    id: 'oll-17',
    name: 'OLL 17 – C Shape',
    category: 'OLL',
    subCategory: 'C',
    alg: "R U R' U R' F R F' U2 R' F R F'",
    alts: [],
    moves: 13,
    recognition: 'C shape: bar on back with one corner sticker on front-right',
    popularity: 5,
    caseShape: 'C',
  },
  {
    id: 'oll-18',
    name: 'OLL 18 – W Shape',
    category: 'OLL',
    subCategory: 'W',
    alg: "r U R' U R U2 r2 U' R U' R' U2 r",
    alts: [],
    moves: 13,
    recognition: 'W pattern: two wide-move lightning shapes connected',
    popularity: 4,
    caseShape: 'W',
  },
  {
    id: 'oll-19',
    name: 'OLL 19 – W Mirror',
    category: 'OLL',
    subCategory: 'W',
    alg: "S' R U R' S U' R' F R F'",
    alts: [],
    moves: 10,
    recognition: 'W shape mirrored',
    popularity: 4,
    caseShape: 'W',
  },
  {
    id: 'oll-20',
    name: 'OLL 20 – Dot (M-slice)',
    category: 'OLL',
    subCategory: 'Dot',
    alg: "r U R' U' M2 U R U' R' U' M'",
    alts: [],
    moves: 11,
    recognition: 'X shape on top or awkward T; M-slice algorithm',
    popularity: 4,
    caseShape: 'X',
  },
  {
    id: 'oll-21',
    name: 'OLL 21 – Solved Cross',
    category: 'OLL',
    subCategory: 'Solved Cross',
    alg: "R U2 R' U' R U R' U' R U' R'",
    alts: [],
    moves: 11,
    recognition: 'Cross done; all 4 corners twisted — two CW, two CCW in diagonal pairs',
    popularity: 7,
    caseShape: 'Cross',
  },
  {
    id: 'oll-22',
    name: 'OLL 22 – Solved Cross Pi',
    category: 'OLL',
    subCategory: 'Solved Cross',
    alg: "R U2 R2 U' R2 U' R2 U2 R",
    alts: [],
    moves: 9,
    recognition: 'Pi – back bar + 2 front stickers forming π',
    popularity: 7,
    caseShape: 'Pi',
  },
  {
    id: 'oll-23',
    name: 'OLL 23 – Solved Cross Blinker',
    category: 'OLL',
    subCategory: 'Solved Cross',
    alg: "R2 D' R U2 R' D R U2 R",
    alts: [],
    moves: 9,
    recognition: 'Cross done; two adjacent corners correct, two twisted CW/CCW',
    popularity: 6,
    caseShape: 'Corners',
  },
  {
    id: 'oll-24',
    name: 'OLL 24 – Solved Cross Blinker Mirror',
    category: 'OLL',
    subCategory: 'Solved Cross',
    alg: "r U R' U' r' F R F'",
    alts: [],
    moves: 8,
    recognition: 'Cross done; mirror of OLL 23 — two adjacent corners correct, reverse twist',
    popularity: 6,
    caseShape: 'Corners',
  },
  {
    id: 'oll-25',
    name: 'OLL 25 – Solved Cross Bowtie',
    category: 'OLL',
    subCategory: 'Solved Cross',
    alg: "F' r U R' U' r' F R",
    alts: [],
    moves: 8,
    recognition: 'Two diagonal corners oriented; bowtie shape',
    popularity: 6,
    caseShape: 'Bowtie',
  },
  {
    id: 'oll-26',
    name: 'OLL 26 – Solved Cross Anti-Sune',
    category: 'OLL',
    subCategory: 'Solved Cross',
    alg: "R U2 R' U' R U' R'",
    alts: [],
    moves: 7,
    recognition: 'Cross done; one corner correct, three twisted CCW — mirror of Sune',
    fingertricks: 'Mirror Sune grip',
    popularity: 9,
    caseShape: 'AntiSune',
  },
  {
    id: 'oll-27',
    name: 'OLL 27 – Solved Cross Sune',
    category: 'OLL',
    subCategory: 'Solved Cross',
    alg: "R U R' U R U2 R'",
    alts: [],
    moves: 7,
    recognition: 'Cross done; one corner correct, three twisted CW — headlights on left front',
    fingertricks: 'Fast RU flick',
    popularity: 10,
    caseShape: 'Sune',
  },
  {
    id: 'oll-28',
    name: 'OLL 28 – Edges Only Right',
    category: 'OLL',
    subCategory: 'Edges Only',
    alg: "r U R' U' M U R U' R'",
    alts: [],
    moves: 9,
    recognition: 'One corner up, edge pointing right; common after bad F2L',
    popularity: 7,
    caseShape: 'Edges Only',
  },
  {
    id: 'oll-29',
    name: 'OLL 29 – P Right Inverted',
    category: 'OLL',
    subCategory: 'P',
    alg: "R U R' U' R U' R' F' U' F R U R'",
    alts: [],
    moves: 13,
    recognition: 'Inverted P on right side',
    popularity: 5,
    caseShape: 'P',
  },
  {
    id: 'oll-30',
    name: 'OLL 30 – P Left Inverted',
    category: 'OLL',
    subCategory: 'P',
    alg: "F U R U2 R' U' R U2 R' U' F'",
    alts: [],
    moves: 11,
    recognition: 'Inverted P on left side',
    popularity: 5,
    caseShape: 'P',
  },
  {
    id: 'oll-31',
    name: 'OLL 31 – Awkward Shape Right',
    category: 'OLL',
    subCategory: 'Awkward',
    alg: "R' U' F U R U' R' F' R",
    alts: [],
    moves: 9,
    recognition: 'S shape on right side of top face',
    popularity: 6,
    caseShape: 'Awkward',
  },
  {
    id: 'oll-32',
    name: 'OLL 32 – Awkward Shape Left',
    category: 'OLL',
    subCategory: 'Awkward',
    alg: "R U B' U' R' U R B R'",
    alts: [],
    moves: 9,
    recognition: 'S shape on left side of top face',
    popularity: 6,
    caseShape: 'Awkward',
  },
  {
    id: 'oll-33',
    name: 'OLL 33 – T Shape',
    category: 'OLL',
    subCategory: 'T',
    alg: "R U R' U' R' F R F'",
    alts: [],
    moves: 8,
    recognition: 'T-bar on front face; classic fast case',
    fingertricks: 'Sexy move + F trigger',
    popularity: 9,
    caseShape: 'T',
  },
  {
    id: 'oll-34',
    name: 'OLL 34 – C Shape',
    category: 'OLL',
    subCategory: 'C',
    alg: "R U R2 U' R' F R U R U' F'",
    alts: [],
    moves: 11,
    recognition: 'C shape; one edge bar + adjacent corner sticker',
    popularity: 6,
    caseShape: 'C',
  },
  {
    id: 'oll-35',
    name: 'OLL 35 – Fish Right',
    category: 'OLL',
    subCategory: 'Fish',
    alg: "R U2 R2 F R F' R U2 R'",
    alts: [],
    moves: 9,
    recognition: 'Fish pointing front-right',
    popularity: 7,
    caseShape: 'Fish',
  },
  {
    id: 'oll-36',
    name: 'OLL 36 – Fish Left',
    category: 'OLL',
    subCategory: 'Fish',
    alg: "L' U' L U' L' U L U L F' L' F",
    alts: [],
    moves: 12,
    recognition: 'Fish pointing front-left',
    popularity: 6,
    caseShape: 'Fish',
  },
  {
    id: 'oll-37',
    name: 'OLL 37 – Small T',
    category: 'OLL',
    subCategory: 'T',
    alg: "F R U' R' U' R U R' F'",
    alts: [],
    moves: 9,
    recognition: 'Small T shape with one edge and two corners',
    popularity: 6,
    caseShape: 'T',
  },
  {
    id: 'oll-38',
    name: 'OLL 38 – L Shape Columns',
    category: 'OLL',
    subCategory: 'L',
    alg: "R U R' U R U' R' U' R' F R F'",
    alts: [],
    moves: 12,
    recognition: 'Two columns of oriented stickers on opposite sides',
    popularity: 5,
    caseShape: 'L',
  },
  {
    id: 'oll-39',
    name: 'OLL 39 – Big Lightning Right',
    category: 'OLL',
    subCategory: 'Lightning',
    alg: "L F' L' U' L U F U' L'",
    alts: [],
    moves: 9,
    recognition: 'Large lightning bolt on right; 3-edge chain',
    popularity: 5,
    caseShape: 'Lightning',
  },
  {
    id: 'oll-40',
    name: 'OLL 40 – Big Lightning Left',
    category: 'OLL',
    subCategory: 'Lightning',
    alg: "R' F R U R' U' F' U R",
    alts: [],
    moves: 9,
    recognition: 'Large lightning bolt on left; efficient 9-mover',
    popularity: 6,
    caseShape: 'Lightning',
  },
  {
    id: 'oll-41',
    name: 'OLL 41 – Awkward Right',
    category: 'OLL',
    subCategory: 'Awkward',
    alg: "R U R' U R U2 R' F R U R' U' F'",
    alts: [],
    moves: 13,
    recognition: 'Awkward shape: Sune + F trigger combination',
    popularity: 4,
    caseShape: 'Awkward',
  },
  {
    id: 'oll-42',
    name: 'OLL 42 – Awkward Left',
    category: 'OLL',
    subCategory: 'Awkward',
    alg: "R' U' R U' R' U2 R F R U R' U' F'",
    alts: [],
    moves: 13,
    recognition: 'Awkward shape mirrored: Anti-sune + F trigger',
    popularity: 4,
    caseShape: 'Awkward',
  },
  {
    id: 'oll-43',
    name: 'OLL 43 – Hook Shape Left',
    category: 'OLL',
    subCategory: 'Hook',
    alg: "F' U' L' U L F",
    alts: [],
    moves: 6,
    recognition: 'Single sticker visible front-left; very efficient',
    fingertricks: "F' pull, L trigger, F back",
    popularity: 8,
    caseShape: 'Hook',
  },
  {
    id: 'oll-44',
    name: 'OLL 44 – Hook Shape Right',
    category: 'OLL',
    subCategory: 'Hook',
    alg: "f R U R' U' f'",
    alts: [],
    moves: 6,
    recognition: 'Single sticker visible front-right; pairs with OLL 43',
    fingertricks: 'F push, L trigger, F pull',
    popularity: 8,
    caseShape: 'Hook',
  },
  {
    id: 'oll-45',
    name: 'OLL 45 – T Shape Cross',
    category: 'OLL',
    subCategory: 'T',
    alg: "F R U R' U' F'",
    alts: [],
    moves: 6,
    recognition: 'Cross edges done; no corners oriented on top',
    fingertricks: 'F trigger — fastest OLL',
    popularity: 10,
    caseShape: 'Cross',
  },
  {
    id: 'oll-46',
    name: 'OLL 46 – Line Shape Back Right',
    category: 'OLL',
    subCategory: 'Line',
    alg: "R' U' R' F R F' U R",
    alts: [],
    moves: 8,
    recognition: 'Cross done; one corner oriented at back-right',
    popularity: 7,
    caseShape: 'Line',
  },
  {
    id: 'oll-47',
    name: 'OLL 47 – Line Shape Diagonal',
    category: 'OLL',
    subCategory: 'Line',
    alg: "R' U' R' F R F' R' F R F' U R",
    alts: [],
    moves: 12,
    recognition: 'Cross done; two diagonal corners wrong way',
    popularity: 7,
    caseShape: 'Line',
  },
  {
    id: 'oll-48',
    name: 'OLL 48 – Line Shape Adjacent',
    category: 'OLL',
    subCategory: 'Line',
    alg: "F R U R' U' R U R' U' F'",
    alts: [],
    moves: 10,
    recognition: 'Cross done; two adjacent corners need orienting',
    popularity: 6,
    caseShape: 'Line',
  },
  {
    id: 'oll-49',
    name: 'OLL 49 – L Shape Right Bar',
    category: 'OLL',
    subCategory: 'L',
    alg: "r U' r2 U r2 U r2 U' r",
    alts: [],
    moves: 9,
    recognition: 'Cross done; right column has headlights bar',
    popularity: 5,
    caseShape: 'L',
  },
  {
    id: 'oll-50',
    name: 'OLL 50 – L Shape Left Bar',
    category: 'OLL',
    subCategory: 'L',
    alg: "r' U r2 U' r2 U' r2 U r'",
    alts: [],
    moves: 9,
    recognition: 'Cross done; left column has headlights bar',
    popularity: 5,
    caseShape: 'L',
  },
  {
    id: 'oll-51',
    name: 'OLL 51 – Line Shape Front Bar',
    category: 'OLL',
    subCategory: 'Line',
    alg: "f R U R' U' R U R' U' f'",
    alts: [],
    moves: 10,
    recognition: 'Cross done; front face shows headlights bar',
    popularity: 5,
    caseShape: 'Line',
  },
  {
    id: 'oll-52',
    name: 'OLL 52 – Line Shape Back Corners',
    category: 'OLL',
    subCategory: 'Line',
    alg: "R U R' U R U' B U' B' R'",
    alts: [],
    moves: 10,
    recognition: 'Cross done; both back corners need orienting',
    popularity: 5,
    caseShape: 'Line',
  },
  {
    id: 'oll-53',
    name: 'OLL 53 – Hook Shape Wide Right',
    category: 'OLL',
    subCategory: 'Hook',
    alg: "r' U' R U' R' U R U' R' U2 r",
    alts: [],
    moves: 11,
    recognition: 'Cross done; wide-r recognized headlights variant',
    popularity: 4,
    caseShape: 'Hook',
  },
  {
    id: 'oll-54',
    name: 'OLL 54 – Hook Shape Wide Left',
    category: 'OLL',
    subCategory: 'Hook',
    alg: "r U R' U R U' R' U R U2 r'",
    alts: [],
    moves: 11,
    recognition: 'Cross done; wide-r left variant',
    popularity: 4,
    caseShape: 'Hook',
  },
  {
    id: 'oll-55',
    name: 'OLL 55 – Hook Shape Front Corners',
    category: 'OLL',
    subCategory: 'Hook',
    alg: "R U2 R2 U' R U' R' U2 F R F'",
    alts: [],
    moves: 11,
    recognition: 'Cross done; front two corners facing sides',
    popularity: 5,
    caseShape: 'Hook',
  },
  {
    id: 'oll-56',
    name: 'OLL 56 – Hook Shape 3 Corners',
    category: 'OLL',
    subCategory: 'Hook',
    alg: "r' U' r U' R' U R U' R' U R r' U r",
    alts: [],
    moves: 14,
    recognition: 'Cross done; three corners misoriented',
    popularity: 4,
    caseShape: 'Hook',
  },
  {
    id: 'oll-57',
    name: 'OLL 57 – Edges Only Left',
    category: 'OLL',
    subCategory: 'Edges Only',
    alg: "R U R' U' M' U R U' r'",
    alts: [],
    moves: 9,
    recognition: 'H shape with all corners solved; M-slice ending',
    popularity: 5,
    caseShape: 'H',
  },
];

// ───────────── PLL ─────────────
export const pllAlgorithms: Algorithm[] = [
  {
    id: 'pll-ua',
    name: 'PLL Ua – Adjacent Swap',
    category: 'PLL',
    subCategory: 'Edges',
    alg: "M2 U M U2 M' U M2",
    alts: ["R U' R U R U R U' R' U' R2"],
    moves: 7,
    recognition: 'Three edges cycle clockwise; one bar visible',
    fingertricks: 'M-slice flick',
    popularity: 10,
    caseShape: 'U',
  },
  {
    id: 'pll-ub',
    name: 'PLL Ub – Counter-Adjacent Swap',
    category: 'PLL',
    subCategory: 'Edges',
    alg: "M2 U' M U2 M' U' M2",
    alts: ["R2 U R U R' U' R' U' R' U R'"],
    moves: 7,
    recognition: 'Three edges cycle counter-clockwise; one bar visible',
    fingertricks: 'M-slice flick reverse',
    popularity: 10,
    caseShape: 'U',
  },
  {
    id: 'pll-h',
    name: 'PLL H – Opposite Swap',
    category: 'PLL',
    subCategory: 'Edges',
    alg: "M2 U M2 U2 M2 U M2",
    alts: [],
    moves: 7,
    recognition: 'All 4 edges swap in pairs; opposite edges match each other',
    fingertricks: 'Pure M-slice rhythm',
    popularity: 8,
    caseShape: 'H',
  },
  {
    id: 'pll-z',
    name: 'PLL Z – Adjacent Edges Swap',
    category: 'PLL',
    subCategory: 'Edges',
    alg: "M' U M2 U M2 U M' U2 M2",
    alts: [],
    moves: 9,
    recognition: 'Adjacent edges swapped on front and back; Z pattern',
    popularity: 7,
    caseShape: 'Z',
  },
  {
    id: 'pll-aa',
    name: 'PLL Aa – Corner 3-Cycle',
    category: 'PLL',
    subCategory: 'Corners',
    alg: "x R' U R' D2 R U' R' D2 R2 x'",
    alts: [],
    moves: 9,
    recognition: 'Three corners cycle; one headlight on left',
    fingertricks: 'Wide move D2 rhythm',
    popularity: 9,
    caseShape: 'A',
  },
  {
    id: 'pll-ab',
    name: 'PLL Ab – Corner 3-Cycle Mirror',
    category: 'PLL',
    subCategory: 'Corners',
    alg: "x R2 D2 R U R' D2 R U' R x'",
    alts: [],
    moves: 9,
    recognition: 'Three corners cycle; headlight on right',
    fingertricks: 'Mirror Aa',
    popularity: 9,
    caseShape: 'A',
  },
  {
    id: 'pll-e',
    name: 'PLL E – Opposite Corners',
    category: 'PLL',
    subCategory: 'Corners',
    alg: "x' R U' R' D R U R' D' R U R' D R U' R' D' x",
    alts: [],
    moves: 16,
    recognition: 'Two pairs of diagonal corners swapped; no bars visible',
    popularity: 5,
    caseShape: 'E',
  },
  {
    id: 'pll-t',
    name: 'PLL T – Adjacent Corners + Edges',
    category: 'PLL',
    subCategory: 'Mixed',
    alg: "R U R' U' R' F R2 U' R' U' R U R' F'",
    alts: [],
    moves: 14,
    recognition: 'One pair corners swapped + opposite edges swapped',
    fingertricks: 'RU2 then F trigger',
    popularity: 8,
    caseShape: 'T',
  },
  {
    id: 'pll-f',
    name: 'PLL F – Diagonal Swap',
    category: 'PLL',
    subCategory: 'Mixed',
    alg: "R' U' F' R U R' U' R' F R2 U' R' U' R U R' U R",
    alts: [],
    moves: 18,
    recognition: 'Diagonal corners + adjacent edges swapped',
    popularity: 5,
    caseShape: 'F',
  },
  {
    id: 'pll-ja',
    name: 'PLL Ja – J Right',
    category: 'PLL',
    subCategory: 'Mixed',
    alg: "x R2 F R F' R U2 r' U r U2 x'",
    alts: ["R' U L' U2 R U' R' U2 R L"],
    moves: 10,
    recognition: 'J facing right: adjacent corner-edge swap on right',
    popularity: 8,
    caseShape: 'J',
  },
  {
    id: 'pll-jb',
    name: 'PLL Jb – J Left',
    category: 'PLL',
    subCategory: 'Mixed',
    alg: "R U R' F' R U R' U' R' F R2 U' R'",
    alts: [],
    moves: 13,
    recognition: 'J facing left: adjacent corner-edge swap on left',
    popularity: 8,
    caseShape: 'J',
  },
  {
    id: 'pll-ra',
    name: 'PLL Ra – Right Adjacent',
    category: 'PLL',
    subCategory: 'Mixed',
    alg: "R U' R' U' R U R D R' U' R D' R' U2 R'",
    alts: [],
    moves: 14,
    recognition: 'R shape pointing right; corner-edge 3-cycle',
    popularity: 7,
    caseShape: 'R',
  },
  {
    id: 'pll-rb',
    name: 'PLL Rb – Left Adjacent',
    category: 'PLL',
    subCategory: 'Mixed',
    alg: "R' U2 R U2 R' F R U R' U' R' F' R2",
    alts: [],
    moves: 12,
    recognition: 'R shape pointing left; mirror of Ra',
    popularity: 7,
    caseShape: 'R',
  },
  {
    id: 'pll-y',
    name: 'PLL Y – Diagonal Corners',
    category: 'PLL',
    subCategory: 'Mixed',
    alg: "F R U' R' U' R U R' F' R U R' U' R' F R F'",
    alts: [],
    moves: 16,
    recognition: 'Diagonal corners + adjacent edges swapped; Y recognition',
    popularity: 6,
    caseShape: 'Y',
  },
  {
    id: 'pll-na',
    name: 'PLL Na',
    category: 'PLL',
    subCategory: 'N',
    alg: "R U R' U R U R' F' R U R' U' R' F R2 U' R' U2 R U' R'",
    alts: [],
    moves: 22,
    recognition: 'All 4 pieces swap in N pattern; diagonal pairs',
    popularity: 4,
    caseShape: 'N',
  },
  {
    id: 'pll-nb',
    name: 'PLL Nb',
    category: 'PLL',
    subCategory: 'N',
    alg: "R' U L' U2 R U' L R' U L' U2 R U' L U2",
    alts: [],
    moves: 15,
    recognition: 'Mirror of Na; diagonal N swap',
    popularity: 4,
    caseShape: 'N',
  },
  {
    id: 'pll-v',
    name: 'PLL V',
    category: 'PLL',
    subCategory: 'Mixed',
    alg: "R' U R' U' R D' R' D R' U D' R2 U' R2 D R2",
    alts: [],
    moves: 16,
    recognition: 'V shape: two corners and one edge cycle',
    popularity: 6,
    caseShape: 'V',
  },
  {
    id: 'pll-ga',
    name: 'PLL Ga',
    category: 'PLL',
    subCategory: 'G',
    alg: "R2 U R' U R' U' R U' R2 D U' R' U R D'",
    alts: [],
    moves: 14,
    recognition: 'G perm A: bar on back, 3-cycle corners and edges clockwise',
    popularity: 5,
    caseShape: 'G',
  },
  {
    id: 'pll-gb',
    name: 'PLL Gb',
    category: 'PLL',
    subCategory: 'G',
    alg: "R' U' R U D' R2 U R' U R U' R U' R2 D",
    alts: [],
    moves: 14,
    recognition: 'G perm B: bar on front, counter-clockwise cycle',
    popularity: 5,
    caseShape: 'G',
  },
  {
    id: 'pll-gc',
    name: 'PLL Gc',
    category: 'PLL',
    subCategory: 'G',
    alg: "R2 U' R U' R U R' U R2 U D' R U' R' D",
    alts: [],
    moves: 15,
    recognition: 'G perm C: bar on right side; clockwise 3-cycle',
    popularity: 5,
    caseShape: 'G',
  },
  {
    id: 'pll-gd',
    name: 'PLL Gd',
    category: 'PLL',
    subCategory: 'G',
    alg: "R U R' U' D R2 U' R U' R' U R' U R2 D'",
    alts: [],
    moves: 15,
    recognition: 'G perm D: bar on left side; counter-clockwise 3-cycle',
    popularity: 5,
    caseShape: 'G',
  },
];

// ───────────── Advanced ─────────────
export const advancedAlgorithms: Algorithm[] = [
  {
    id: 'adv-sexy',
    name: 'Sexy Move',
    category: 'Advanced',
    subCategory: 'Triggers',
    alg: "R U R' U'",
    alts: [],
    moves: 4,
    recognition: 'Fundamental trigger used in many algorithms',
    fingertricks: 'Index R flick',
    popularity: 10,
    caseShape: 'Trigger',
  },
  {
    id: 'adv-sledge',
    name: 'Sledgehammer',
    category: 'Advanced',
    subCategory: 'Triggers',
    alg: "R' F R F'",
    alts: [],
    moves: 4,
    recognition: 'F trigger variant — opposite of sexy move',
    fingertricks: "Ring R' then pinch F",
    popularity: 9,
    caseShape: 'Trigger',
  },
  {
    id: 'adv-hedge',
    name: 'Hedgehammer',
    category: 'Advanced',
    subCategory: 'Triggers',
    alg: "F R' F' R",
    alts: [],
    moves: 4,
    recognition: 'Mirror of sledgehammer',
    popularity: 8,
    caseShape: 'Trigger',
  },
  {
    id: 'adv-niklas',
    name: 'Niklas',
    category: 'Advanced',
    subCategory: 'Corners',
    alg: "R U' L' U R' U' L",
    alts: [],
    moves: 7,
    recognition: 'Opposite corner 3-cycle, no edges disturbed',
    popularity: 7,
    caseShape: 'Corners',
  },
  {
    id: 'adv-commutator',
    name: 'Basic Commutator',
    category: 'Advanced',
    subCategory: 'Commutators',
    alg: "R U R' U'",
    alts: ["[R, U]"],
    moves: 4,
    recognition: 'Cycle pieces without disturbing others; building block of BLD',
    popularity: 8,
    caseShape: 'Commutator',
  },
  {
    id: 'adv-m-slice',
    name: 'M-Slice',
    category: 'Advanced',
    subCategory: 'Slices',
    alg: "M' U M U2 M' U M",
    alts: [],
    moves: 7,
    recognition: 'Orient and cycle M-slice edges',
    fingertricks: 'Thumb M pull',
    popularity: 7,
    caseShape: 'MSlice',
  },
  {
    id: 'adv-oll-skip',
    name: 'OLL Skip Setup',
    category: 'Advanced',
    subCategory: 'Shortcuts',
    alg: "x2 R U R' U R U2 R' x2",
    alts: [],
    moves: 8,
    recognition: 'Forces an OLL skip in certain cube states',
    popularity: 5,
    caseShape: 'Skip',
  },
];

export const allAlgorithms: Algorithm[] = [
  ...f2lAlgorithms,
  ...ollAlgorithms,
  ...pllAlgorithms,
  ...advancedAlgorithms,
];

export function searchAlgorithms(query: string, category?: Category): Algorithm[] {
  const q = query.toLowerCase().trim();
  return allAlgorithms.filter((alg) => {
    const matchesCategory = !category || alg.category === category;
    if (!q) return matchesCategory;
    return (
      matchesCategory &&
      (alg.name.toLowerCase().includes(q) ||
        alg.alg.toLowerCase().includes(q) ||
        alg.recognition.toLowerCase().includes(q) ||
        alg.id.toLowerCase().includes(q) ||
        alg.subCategory?.toLowerCase().includes(q))
    );
  });
}

export function getAlgorithmById(id: string): Algorithm | undefined {
  return allAlgorithms.find((a) => a.id === id);
}

/**
 * Whether the algorithm's NET whole-cube rotation is the identity (all six
 * centres return home). Only x/y/z tokens are composed, so a balanced rotation
 * like `x … x'` is neutral. Mirrors `isRotationNeutral` in `lib/cubeImage.ts`
 * (kept inline so this module stays dependency-free and independently loadable
 * by the test runner).
 */
function isRotationNeutral(alg: string): boolean {
  type Vec = [number, number, number];
  let up: Vec = [0, 1, 0];
  let front: Vec = [0, 0, 1];
  const rotX = (v: Vec): Vec => [v[0], v[2], -v[1]];
  const rotY = (v: Vec): Vec => [-v[2], v[1], v[0]];
  const rotZ = (v: Vec): Vec => [v[1], -v[0], v[2]];
  for (const tok of alg.trim().split(/\s+/).filter(Boolean)) {
    const m = /^([xyz])(2'|'2|2|')?$/.exec(tok);
    if (!m) continue;
    const fn = m[1] === 'x' ? rotX : m[1] === 'y' ? rotY : rotZ;
    const count = m[2] === "'" ? 3 : m[2] ? 2 : 1;
    for (let i = 0; i < count; i++) {
      up = fn(up);
      front = fn(front);
    }
  }
  return up[1] === 1 && up[0] === 0 && up[2] === 0 && front[2] === 1 && front[0] === 0 && front[1] === 0;
}

/**
 * The algorithm string best suited for the recognition image. A net whole-cube
 * rotation would shift the cube relative to the case mask, so the first
 * rotation-neutral candidate (main, then alternatives) is preferred.
 */
export function getVizAlg(algorithm: Algorithm): string {
  return [algorithm.alg, ...algorithm.alts].find(isRotationNeutral) ?? algorithm.alg;
}
